id: P5459BBE1
initial_creation_type: input
source_metadata:
  Title: Hetutattvopadeśaḥ
  Editor: Chattopadhyaya, D.C.
  Publisher: Pilgrims Book Pvt.Ltd
  Place of Publication: Delhi
  Year: '1998'
  Hetutattvopadeśaḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2008'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
created_at: '2022-03-08T16:48:34.643305'
last_modified_at: '2022-03-08T16:48:34.643314'
